### ISSUE TITLE
Tagging

### ISSUE THREAD

**Issue by JamesP2** [JamesP2/ReviewSite#12]
Automagical (Will's choice of word) tagging for articles. Allow multiple tags for each article, bootstrap autocomplete JS for suggesting existing tags.

Creating a new tag should automatically add it to the database. Tags must be searchable and have a many-many index with articles.

**Comment by Tzabar1994** [comment]
I wouldn't necessarily do this as you may end up having web only articles - especially if print is only 6 times a year.

(To put comment in context this was when specific print issue tagging was being discussed)

**Comment by JamesP2** [comment]
This is now implemented (thanks Will!).
