### ISSUE TITLE
Footer Content

### ISSUE THREAD

**Issue by JamesP2** [JamesP2/ReviewSite#28]
@Spiruel will provide a disclaimer.

There must be a link to the school website.

Valid CSS/HTML stuff? although it probably isn't.

Anything else that might need to go there for release.

**Comment by Spiruel** [comment]
Something like 'this website with the articles included on it are purely the work of THEREVIEW, which consists of sixth form students from William Howard School' with William Howard school linking to school website

**Comment by Tzabar1994** [comment]
note: capatalise that properly ie TheReview
Or it looks like ThereView.
Which I guess it is as well!
