### ISSUE TITLE
Randomizing Front Page

### ISSUE THREAD

**Issue by Tzabar1994** [JamesP2/ReviewSite#31]
It would be Cool if the Front Page's tiles were a random selection of the most recent (20?) news items. An enhancement to that would be some kind of transition/animation (perhaps one tile for each category that rotated between the last 3 stories in that category?).

**Comment by JamesP2** [comment]
This is impractical due to image resizing on-the-fly being fairly impossible (to get nice results, anyway) and because some things like crosswords shouldn't be there anyway.
