### ISSUE TITLE
Add meta tags?

### ISSUE THREAD

**Issue by Spiruel** [JamesP2/ReviewSite#39]

**Comment by JamesP2** [comment]
Of course, if you suggest some.

**Comment by Spiruel** [comment]
Thanks - is it about 10 keywords you need?

**Comment by Spiruel** [comment]
Don't know how many you need, so here you are:
William Howard School Sixth Form Student Publication Newspaper Magazine theReview The WHS Review online articles cumbria academy

**Comment by JamesP2** [comment]
Commit 8d4cbe4305 closes this issue.
